# 项目相关配置
main:
  #名称
  name: syndo-tax
  #版本
  version: 2.0.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/profile，Linux配置 /home/profile）
  profile: D:/profile
  #profile: /home/profile
  # 获取ip地址开关
  addressEnabled: false
  # 日志存放路径 示例（ Windows配置D:/profile/logs，Linux配置 /home/logs）
  logpath: D:/profile/logs
  #logpath: /home/logs
  # 指标导入模板路径,若以.开头表示相对classpath的路径
  #tmpFile: ../../src/main/resources/tmpfile/
  #tmpFile: /home/tmpfile
  tmpFile: D:/projects/tmpfile/

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 反向代理
proxys:
  list:
    - name: map
      url: /main/map/wms/*
      targetUrl: http://192.168.10.4:58080/geowebcache/service/wms

# 日志配置
logging:
  level:
    com.syndo: debug
    org.springframework: warn

# 用户配置
user:
  password:
    #密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5
    # 通用密码\万能密码
    generalPassword: syndo@888888
  
# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    #国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid-mysql
  #文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 60MB
      # 设置总上传的文件大小
      max-request-size: 100MB
  # 服务模块
  devtools:
    restart:
      #热部署开关
      enabled: true
  # redis配置
  redis:
    # 地址
    #host: 192.168.10.4
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 密码（默认为空；正式环境必须设计密码，否则会注入病毒！）
    password: 123456
    #password:
    # 数据库索引（默认为0）
    database: 11
    # 连接超时时间
    timeout: 60s
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
        
# MyBatis
mybatis-plus:
    # 搜索指定包别名
    typeAliasesPackage: com.syndo.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Shiro
shiro:
  user:
    # 登录地址
    #loginUrl: http://192.168.100.52:3000
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: false
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true    # 设置Cookie的过期时间，天为单位

    maxAge: 30
    # 设置密钥，务必保持唯一性
    # 生成方式，直接拷贝到main运行即可：org.apache.shiro.codec.Base64.encodeToString(CipherUtils.generateNewKey(128, "AES").getEncoded())
    # 默认启动生成随机秘钥，随机秘钥会导致之前客户端RememberMe Cookie无效，如设置固定秘钥RememberMe Cookie则有效
    cipherKey: 86Z8y0hx3Mx7sVtAmHTltg==
    # 设置Cookie名称，务必保持唯一性（防止多项目session冲突）
    cookieName: syndoTaxSessionId

  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false
  filter:
    # 白名单过滤链定义（多个用逗号分隔）
    chainDefinition: /app/**,/bigscreen/**,/system/**,/magic-api/**,/validateLogin/**
    
# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*,/module/*

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  
# magic-api配置 https://www.ssssssss.org/magic-api/pages/config/spring-boot/
magic-api:
  # 配置web页面入口
  web: /magic/web
  resource:
    # 配置接口资源存储位置，可选file、database、redis
    type: database
    # 存储表名
    tableName: pub_magic_api_file
    # 使用database、redis存储时的key前缀
    prefix: /magic-api
    # 是否是只读模式
    readonly: false

# 单点登录配置
cas:
  prefixUrl: http://192.168.100.77:8081/cas
  #prefixUrl: http://localhost:8443/cas
  localUrl: http://192.168.100.43:8080/validateLogin/tick
  localBaseUrl: http://192.168.100.43:8080/
  httpGetUrl: http://192.168.100.77:8081/cas/login?service=